version: '3.3'
services:
  backend:
    build:
      context: ./backend
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
